#!/bin/sh

if ./build.sh -DCMAKE_BUILD_TYPE=Release -DENABLE_SANITIZER_THREAD=FALSE -DENABLE_SANITIZER_ADDRESS=FALSE -DENABLE_SANITIZER_LEAK=FALSE -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=FALSE -DENABLE_SANITIZER_MEMORY=FALSE -DTESTS=FALSE $@; then
echo "Built tests";
else 
echo "Could not build tests";
exit 1 
fi
